import sys
import os


def ir_to_script(ir):
    category = ir["category"]
    domain   = ir["domain"]
    geo      = ir["geometry"]
    mat      = ir["material"]
    physics  = ir["physics"]
    exc      = ir.get("excitation")
    init     = ir["initialization"]
    solver   = ir["solver"]
    outputs  = ir["outputs"]

    lines = []

    lines.append(f"// MuMax3 simulation — generated by NL2Sim")
    lines.append(f"// Category: {category}")
    lines.append(f"// Material: {mat['name']}")
    lines.append(f"// Geometry: {geo['size_x_nm']:.0f}x{geo['size_y_nm']:.0f}x{geo['size_z_nm']:.0f} nm")
    lines.append("")


    lines.append("// ── Grid ──────────────────────────────────────────────")
    lines.append(f"SetGridsize({domain['nx']}, {domain['ny']}, {domain['nz']})")
    lines.append(
        f"SetCellsize({domain['dx_m']:.4e}, {domain['dy_m']:.4e}, {domain['dz_m']:.4e})"
    )
    lines.append("")

    shape = geo["shape"]
    if shape in ("cylinder", "disk"):
        r = min(geo["size_x_nm"], geo["size_y_nm"]) / 2 * 1e-9
        h = geo["size_z_nm"] * 1e-9
        lines.append("// ── Geometry ──────────────────────────────────────────")
        lines.append(f"SetGeom(cylinder({r:.4e}, {h:.4e}))")
        lines.append("")
    elif shape == "ellipse":
        rx = geo["size_x_nm"] / 2 * 1e-9
        ry = geo["size_y_nm"] / 2 * 1e-9
        lines.append("// ── Geometry ──────────────────────────────────────────")
        lines.append(f"SetGeom(ellipse({rx:.4e}, {ry:.4e}))")
        lines.append("")
    # rectangle = default, no SetGeom needed


    lines.append("// ── Material ──────────────────────────────────────────────")
    lines.append(f"Msat  = {mat['Msat_Am']:.4e}   // {mat['Msat_Am']/1e3:.0f} kA/m")
    lines.append(f"Aex   = {mat['Aex_Jm']:.4e}    // {mat['Aex_Jm']*1e12:.1f} pJ/m")
    lines.append(f"alpha = {mat['alpha']}")

    if mat.get("Ku1_Jm3") is not None:
        lines.append(f"Ku1   = {mat['Ku1_Jm3']:.4e}   // anisotropy constant")
        lines.append( "anisU = vector(0, 0, 1)         // easy axis along z")

    if mat.get("DMI_Jm2") is not None:
        lines.append(f"Dind  = {mat['DMI_Jm2']:.4e}   // interfacial DMI")

    if mat.get("Temp_K") is not None and physics.get("use_thermal"):
        lines.append(f"Temp  = {mat['Temp_K']:.1f}          // temperature in K")

    lines.append("")

    # ── Initial magnetisation ─────────────────────────────────────────────────
    lines.append("// ── Initial state ─────────────────────────────────────────")
    init_type = init["type"]
    init_dir  = init.get("direction", "+x")

    if init_type == "two_domain":
        lines.append("m = twoDomain(1, 0, 0, -1, 0, 0)  // head-to-head domain wall")
    elif init_type == "uniform_then_nucleate":
        lines.append("m = uniform(0, 0, 1)   // start uniform out-of-plane")
        # Nucleate a skyrmion by reversing a small circle
        r_sky = min(geo["size_x_nm"], geo["size_y_nm"]) * 0.05 * 1e-9
        lines.append(f"m.setInShape(circle({r_sky:.3e}), uniform(0, 0, -1))")
    elif init_type == "vortex":
        lines.append("m = vortex(1, 1)   // vortex state")
    elif "+x" in str(init_dir) or init_dir == "x":
        lines.append("m = uniform(1, 0, 0)")
    elif "+z" in str(init_dir) or init_dir == "z":
        lines.append("m = uniform(0, 0, 1)")
    else:
        lines.append("m = uniform(1, 0, 0)   // default: uniform along +x")
    lines.append("")

    # ── Relax ─────────────────────────────────────────────────────────────────
    lines.append("// ── Energy minimisation ───────────────────────────────────")
    lines.append("relax()")
    lines.append("")

    if exc is not None:
        lines.append("// ── Excitation ────────────────────────────────────────────")

        if exc["type"] == "dc_field":
            B = exc["B_T"]
            d = exc.get("direction", "x")
            bx = B if d == "x" else 0.0
            by = B if d == "y" else 0.0
            bz = B if d == "z" else 0.0
            lines.append(
                f"B_ext = vector({bx:.4e}, {by:.4e}, {bz:.4e})   // {B*1e3:.1f} mT along {d}"
            )

        elif exc["type"] == "pulse":
            B     = exc["B_T"]
            d     = exc.get("direction", "x")
            dur   = exc.get("pulse_ns", 5.0) * 1e-9
            rise  = min(0.2e-9, dur * 0.1)   # 10% rise time
            bx    = B if d == "x" else 0.0
            by    = B if d == "y" else 0.0
            bz    = B if d == "z" else 0.0
            lines.append(f"// Field pulse: {B*1e3:.1f} mT along {d}, duration {dur*1e9:.1f} ns")
            lines.append(
                f"B_ext = vector({bx:.4e}*pulse({rise:.3e},{dur:.3e},{rise:.3e}), "
                f"{by:.4e}*pulse({rise:.3e},{dur:.3e},{rise:.3e}), "
                f"{bz:.4e}*pulse({rise:.3e},{dur:.3e},{rise:.3e}))"
            )

        elif exc["type"] == "ac_field":
            B    = exc["B_T"]
            freq = exc.get("frequency_GHz", 5.0) * 1e9
            bz   = exc.get("B_T", 0.1)   # DC bias along z
            lines.append(f"// AC excitation at {freq/1e9:.1f} GHz + DC bias")
            lines.append(f"B_ext = vector({B:.4e}*sin(2*pi*{freq:.4e}*t), 0, {bz:.4e})")

        elif exc["type"] == "current":
            Jc     = exc["Jc_Am2"]
            lines.append(f"// Spin current: Jc = {Jc:.2e} A/m2 along x")
            lines.append(f"Jc = vector({Jc:.4e}, 0, 0)")
            if exc.get("pol") is not None:
                lines.append(f"pol = {exc['pol']:.2f}   // spin polarisation")
            if exc.get("xi_DL") is not None:
                lines.append(f"xi_DL = {exc['xi_DL']:.2f}   // SOT efficiency")

        lines.append("")

    # ── Outputs ───────────────────────────────────────────────────────────────
    if solver["mode"] != "relax_only":
        lines.append("// ── Outputs ───────────────────────────────────────────────")
        dt_save = solver["dt_save_s"]

        m_outputs = [o for o in outputs if o["quantity"] == "m"]
        if m_outputs:
            lines.append(f"autosave(m, {dt_save:.3e})   // save m every {dt_save*1e12:.0f} ps")

        table_outputs = [o for o in outputs if o["schedule"] == "table"]
        if table_outputs:
            lines.append(f"tableautosave({dt_save:.3e})")
            for o in table_outputs:
                qty = o["quantity"]
                lines.append(f"tableadd({qty})")

        lines.append("")

    if solver["mode"] != "relax_only":
        t_total = solver["t_total_s"]
        lines.append("// ── Run dynamics ──────────────────────────────────────────")
        lines.append(f"run({t_total:.3e})   // simulate for {t_total*1e9:.1f} ns")

    return "\n".join(lines) + "\n"


LLM_CODEGEN_SYSTEM = """You are an expert MuMax3 micromagnetics simulation programmer.
Generate valid MuMax3 scripts from a structured simulation specification.
Return ONLY the MuMax3 script text - no explanation, no markdown, no backticks.
"""

LLM_CODEGEN_PROMPT = """
Generate a valid MuMax3 simulation script for this specification:

Category: {category}
Material: {material_name}, Msat={Msat_kAm} kA/m, Aex={Aex_pJm} pJ/m, alpha={alpha}
Geometry: {shape}, {size_x}x{size_y}x{size_z} nm
Grid: {nx}x{ny}x{nz} cells
Physics: {physics_list}
Initial state: {init_type}
Excitation: {excitation_desc}
Simulation time: {sim_time_ns} ns
Save interval: {save_ps} ps

Important rules for MuMax3:
1. Always start with SetGridsize and SetCellsize
2. Use relax() before dynamics to find equilibrium
3. Use autosave(m, dt) for magnetisation snapshots
4. Use tableadd() for scalar quantities, tableautosave(dt) to save them
5. End with run(t) for dynamic simulations

Generate the complete script:
"""


def generate_with_llm(ir, llm_client):
    mat    = ir["material"]
    geo    = ir["geometry"]
    domain = ir["domain"]
    physics = ir["physics"]
    exc    = ir.get("excitation")
    init   = ir["initialization"]
    solver = ir["solver"]

    physics_list = []
    if physics["use_exchange"]:  physics_list.append("Exchange")
    if physics["use_demag"]:     physics_list.append("Demag")
    if physics["use_zeeman"]:    physics_list.append("Zeeman")
    if physics["use_dmi"]:       physics_list.append("DMI")
    if physics["use_anisotropy"]: physics_list.append("Anisotropy")
    if physics["use_stt"]:       physics_list.append("STT")
    if physics["use_sot"]:       physics_list.append("SOT")
    if physics["use_thermal"]:   physics_list.append("Thermal")

    if exc:
        if exc["type"] == "dc_field":
            exc_desc = f"DC field {exc['B_T']*1e3:.1f} mT along {exc.get('direction','x')}"
        elif exc["type"] == "pulse":
            exc_desc = f"Field pulse {exc['B_T']*1e3:.1f} mT, {exc.get('pulse_ns',5)} ns"
        elif exc["type"] == "ac_field":
            exc_desc = f"AC field {exc.get('frequency_GHz',5)} GHz"
        elif exc["type"] == "current":
            exc_desc = f"Current {exc['Jc_Am2']/1e6:.1f} MA/m2"
        else:
            exc_desc = str(exc)
    else:
        exc_desc = "None"

    prompt = LLM_CODEGEN_PROMPT.format(
        category=ir["category"],
        material_name=mat["name"],
        Msat_kAm=mat["Msat_Am"] / 1e3,
        Aex_pJm=mat["Aex_Jm"] * 1e12,
        alpha=mat["alpha"],
        shape=geo["shape"],
        size_x=geo["size_x_nm"],
        size_y=geo["size_y_nm"],
        size_z=geo["size_z_nm"],
        nx=domain["nx"],
        ny=domain["ny"],
        nz=domain["nz"],
        physics_list=", ".join(physics_list),
        init_type=init["type"],
        excitation_desc=exc_desc,
        sim_time_ns=solver["t_total_s"] * 1e9,
        save_ps=solver["dt_save_s"] * 1e12,
    )

    response = llm_client.complete(
        prompt=prompt,
        system=LLM_CODEGEN_SYSTEM,
        max_tokens=1200,
        temperature=0.2,
        json_mode=False,
    )

    return response.text.strip()


def generate_script(ir, llm_client=None, prefer_template=True):
    if prefer_template:
        try:
            script = ir_to_script(ir)
            return script, "template"
        except Exception as e:
            print(f"  [CodeGen] Template failed: {e}")
            if llm_client is None:
                raise

    if llm_client is not None:
        print("  [CodeGen] Using LLM for code generation")
        script = generate_with_llm(ir, llm_client)
        return script, "llm"

    raise RuntimeError("Template generation failed and no LLM client provided")
