"""
ir_to_mumax3.py
===============
Converts a structured IR (Intermediate Representation) into a MuMax3 script.

This is the FORWARD direction:
  IR dict  →  MuMax3 .mx3 script text

This module is the "back-end" of our compiler.
It is completely deterministic — given the same IR, it always produces
the same script. No randomness, no LLM calls.

This is used in:
  - The code generator (pipeline/code_generator.py) as the template method
  - Test cases where we need to round-trip: IR → script → IR

Usage:
    from validation.ir_to_mumax3 import emit_script

    ir = {
        "category": "field_driven",
        "domain":   {"nx": 512, "ny": 128, "nz": 1,
                     "dx_m": 1e-9, "dy_m": 1e-9, "dz_m": 5e-9},
        "material": {"Msat_Am": 800e3, "Aex_Jm": 13e-12, "alpha": 0.01},
        ...
    }
    script = emit_script(ir)
    print(script)
"""


def emit_script(ir):
    """
    Generate a MuMax3 .mx3 script from an IR dict.

    This function calls the individual section emitters in order
    and joins their output with blank lines.

    Returns: A string containing the complete MuMax3 script.
    """
    sections = []

    sections.append(_emit_header(ir))
    sections.append(_emit_grid(ir))

    geom = _emit_geometry(ir)
    if geom:
        sections.append(geom)

    sections.append(_emit_material(ir))

    init = _emit_initialization(ir)
    if init:
        sections.append(init)

    sections.append(_emit_relax(ir))

    exc = _emit_excitation(ir)
    if exc:
        sections.append(exc)

    out = _emit_outputs(ir)
    if out:
        sections.append(out)

    solver = _emit_solver(ir)
    if solver:
        sections.append(solver)

    # Join sections with a blank line between each
    return "\n\n".join(s.strip() for s in sections if s.strip()) + "\n"


# ─── Section Emitters ─────────────────────────────────────────────────────────

def _emit_header(ir):
    """Top comment block describing the simulation."""
    cat  = ir.get("category", "unknown")
    geo  = ir.get("geometry", {})
    mat  = ir.get("material", {})

    x = geo.get("size_x_nm", 0)
    y = geo.get("size_y_nm", 0)
    z = geo.get("size_z_nm", 0)
    name = mat.get("name", "unknown material")

    lines = [
        "// ─────────────────────────────────────────────────────",
        f"// MuMax3 simulation  |  generated by NL2Sim",
        f"// Category  : {cat}",
        f"// Material  : {name}",
        f"// Geometry  : {x:.0f} × {y:.0f} × {z:.0f} nm",
        "// ─────────────────────────────────────────────────────",
    ]
    return "\n".join(lines)


def _emit_grid(ir):
    """Grid and cell size setup — always required."""
    d = ir.get("domain", {})
    nx = d.get("nx", 128)
    ny = d.get("ny", 128)
    nz = d.get("nz", 1)
    dx = d.get("dx_m", 2e-9)
    dy = d.get("dy_m", 2e-9)
    dz = d.get("dz_m", 5e-9)

    lines = [
        "// Grid",
        f"SetGridsize({nx}, {ny}, {nz})",
        f"SetCellsize({dx:.4e}, {dy:.4e}, {dz:.4e})",
    ]
    return "\n".join(lines)


def _emit_geometry(ir):
    """
    Geometry mask — only emitted if the shape is NOT a plain rectangle.
    Plain rectangles are the default and need no SetGeom call.
    """
    geo   = ir.get("geometry", {})
    shape = geo.get("shape", "rectangle")

    if shape in ("rectangle", "rect", None):
        return None   # default shape, no SetGeom needed

    size_x = geo.get("size_x_nm", 200) * 1e-9
    size_y = geo.get("size_y_nm", 200) * 1e-9
    size_z = geo.get("size_z_nm", 10)  * 1e-9

    if shape in ("cylinder", "disk"):
        radius = min(size_x, size_y) / 2
        return f"// Geometry\nSetGeom(cylinder({radius:.4e}, {size_z:.4e}))"

    if shape == "ellipse":
        rx = size_x / 2
        ry = size_y / 2
        return f"// Geometry\nSetGeom(ellipse({rx:.4e}, {ry:.4e}))"

    # Unknown shape — skip
    return None


def _emit_material(ir):
    """Material parameters — Msat, Aex, alpha, and optional properties."""
    mat     = ir.get("material", {})
    physics = ir.get("physics",  {})

    Msat  = mat.get("Msat_Am",  800e3)
    Aex   = mat.get("Aex_Jm",   13e-12)
    alpha = mat.get("alpha",    0.01)
    Ku1   = mat.get("Ku1_Jm3")
    DMI   = mat.get("DMI_Jm2")
    Temp  = mat.get("Temp_K")

    lines = ["// Material"]
    lines.append(f"Msat  = {Msat:.4e}   // {Msat/1e3:.0f} kA/m")
    lines.append(f"Aex   = {Aex:.4e}    // {Aex*1e12:.1f} pJ/m")
    lines.append(f"alpha = {alpha}")

    if Ku1 is not None and physics.get("use_anisotropy"):
        lines.append(f"Ku1   = {Ku1:.4e}   // uniaxial anisotropy constant")
        lines.append("anisU = vector(0, 0, 1)  // easy axis along z (perpendicular)")

    if DMI is not None and physics.get("use_dmi"):
        lines.append(f"Dind  = {DMI:.4e}   // interfacial DMI")

    if Temp is not None and Temp > 0 and physics.get("use_thermal"):
        lines.append(f"Temp  = {Temp:.1f}   // temperature in K")

    return "\n".join(lines)


def _emit_initialization(ir):
    """Initial magnetisation state."""
    init = ir.get("initialization", {})
    geo  = ir.get("geometry", {})

    init_type = init.get("type", "uniform")
    direction = init.get("direction", "+x")

    lines = ["// Initial magnetisation"]

    if init_type == "two_domain":
        lines.append("m = twoDomain(1, 0, 0, -1, 0, 0)  // head-to-head domain wall")

    elif init_type == "uniform_then_nucleate":
        # Uniform out-of-plane, then nucleate skyrmion by reversing a small region
        lines.append("m = uniform(0, 0, 1)")
        r_sky = min(
            geo.get("size_x_nm", 200),
            geo.get("size_y_nm", 200)
        ) * 0.05e-9  # 5% of the smaller dimension
        lines.append(f"m.setInShape(circle({r_sky:.3e}), uniform(0, 0, -1))")

    elif init_type == "vortex":
        lines.append("m = vortex(1, 1)  // vortex with positive chirality and core")

    elif "+z" in str(direction):
        lines.append("m = uniform(0, 0, 1)")

    elif "-z" in str(direction):
        lines.append("m = uniform(0, 0, -1)")

    elif "-x" in str(direction):
        lines.append("m = uniform(-1, 0, 0)")

    else:
        lines.append("m = uniform(1, 0, 0)  // start uniform along +x")

    return "\n".join(lines)


def _emit_relax(ir):
    """Energy minimisation step — almost always present."""
    solver = ir.get("solver", {})
    mode   = solver.get("mode", "relax_only")

    lines = ["// Find equilibrium before dynamics"]
    lines.append("relax()")

    # For simple_relax category, save after relaxing
    if mode == "relax_only":
        lines.append("save(m)  // save equilibrium magnetisation")

    return "\n".join(lines)


def _emit_excitation(ir):
    """Applied excitation — field, pulse, or current."""
    exc     = ir.get("excitation")
    physics = ir.get("physics", {})

    if exc is None:
        return None

    lines = ["// Excitation"]
    exc_type = exc.get("type", "dc_field")

    if exc_type == "dc_field" and physics.get("use_zeeman"):
        B    = exc.get("B_T", 0.01)
        dirn = exc.get("direction", "+x")
        bx = B if "x" in str(dirn) else 0.0
        by = B if "y" in str(dirn) else 0.0
        bz = B if "z" in str(dirn) else 0.0
        # Correct sign
        if dirn and "-" in str(dirn):
            bx, by, bz = -bx, -by, -bz
        lines.append(f"// DC field: {B*1e3:.1f} mT along {dirn}")
        lines.append(f"B_ext = vector({bx:.4e}, {by:.4e}, {bz:.4e})")

    elif exc_type == "pulse" and physics.get("use_zeeman"):
        B     = exc.get("B_T", 0.01)
        dirn  = exc.get("direction", "+x")
        dur   = exc.get("pulse_ns", 5.0) * 1e-9
        rise  = min(0.2e-9, dur * 0.1)
        bx = B if "x" in str(dirn) else 0.0
        by = B if "y" in str(dirn) else 0.0
        bz = B if "z" in str(dirn) else 0.0
        lines.append(f"// Pulse: {B*1e3:.1f} mT, {dur*1e9:.1f} ns duration")
        lines.append(
            f"B_ext = vector({bx:.4e} * pulse({rise:.3e}, {dur:.3e}, {rise:.3e}),\n"
            f"               {by:.4e} * pulse({rise:.3e}, {dur:.3e}, {rise:.3e}),\n"
            f"               {bz:.4e} * pulse({rise:.3e}, {dur:.3e}, {rise:.3e}))"
        )

    elif exc_type == "ac_field" and physics.get("use_zeeman"):
        B    = exc.get("B_T", 0.001)
        freq = exc.get("frequency_GHz", 5.0) * 1e9
        bz   = exc.get("B_T", 0.05)  # DC bias along z
        lines.append(f"// AC sinusoidal excitation at {freq/1e9:.1f} GHz")
        lines.append(f"B_ext = vector({B:.4e} * sin(2*pi*{freq:.4e}*t), 0, {bz:.4e})")

    elif exc_type == "current":
        Jc    = exc.get("Jc_Am2", 1e12)
        pol   = exc.get("pol", 0.6)
        xi_DL = exc.get("xi_DL")
        lines.append(f"// Current density: {Jc:.2e} A/m2 along x")
        lines.append(f"Jc    = vector({Jc:.4e}, 0, 0)")
        if pol and not xi_DL:   # STT
            lines.append(f"pol   = {pol:.2f}   // spin polarisation")
            lines.append("xi    = 0.05   // non-adiabaticity")
        if xi_DL:               # SOT
            lines.append(f"xi_DL = {xi_DL:.2f}   // SOT damping-like efficiency")
            lines.append("xi_FL = 0.0    // field-like efficiency (set if needed)")

    return "\n".join(lines) if len(lines) > 1 else None


def _emit_outputs(ir):
    """Output configuration — autosave, tableadd, tableautosave."""
    solver  = ir.get("solver", {})
    outputs = ir.get("outputs", [])

    if solver.get("mode") == "relax_only":
        return None   # no time-dependent outputs needed

    dt = solver.get("dt_save_s", 1e-10)

    # Separate m snapshots from table quantities
    snap_quantities  = [o["quantity"] for o in outputs if o.get("schedule") == "autosave"]
    table_quantities = [o["quantity"] for o in outputs if o.get("schedule") == "table"]

    if not snap_quantities and not table_quantities:
        # Default: save m and E_total
        snap_quantities  = ["m"]
        table_quantities = ["E_total", "E_exch", "E_demag"]

    lines = ["// Outputs"]

    if snap_quantities:
        for q in snap_quantities:
            lines.append(f"autosave({q}, {dt:.3e})   // every {dt*1e12:.0f} ps")

    if table_quantities:
        lines.append(f"tableautosave({dt:.3e})")
        for q in table_quantities:
            lines.append(f"tableadd({q})")

    return "\n".join(lines)


def _emit_solver(ir):
    """Solver call — run(t) for dynamic simulations."""
    solver = ir.get("solver", {})
    mode   = solver.get("mode", "relax_only")

    if mode == "relax_only":
        return None   # relax() was already emitted above

    t_total = solver.get("t_total_s", 5e-9)
    lines = [
        "// Run dynamics",
        f"run({t_total:.4e})   // {t_total*1e9:.1f} ns total",
    ]
    return "\n".join(lines)
